# Generated by Django 6.0.4 on 2026-04-15 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organs_donating', models.JSONField(default=list)),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('smoking_status', models.CharField(choices=[('never', 'Never Smoked'), ('former', 'Former Smoker'), ('current', 'Current Smoker')], default='never', max_length=20)),
                ('alcohol_use', models.CharField(choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular')], default='never', max_length=20)),
                ('drug_use', models.BooleanField(default=False)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('avg_sleep', models.FloatField(blank=True, null=True)),
                ('last_medical_checkup', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True)),
                ('preferred_hospital', models.CharField(blank=True, max_length=255)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('willing_to_travel', models.BooleanField(default=True)),
                ('max_travel_distance', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organs_needed', models.JSONField(default=list)),
                ('urgency_level', models.CharField(choices=[('low', 'Low - Can wait months'), ('medium', 'Medium - Needs within weeks'), ('high', 'High - Needs within days'), ('critical', 'Critical - Immediate need')], default='medium', max_length=20)),
                ('medical_condition', models.TextField(blank=True)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('current_treatment', models.TextField(blank=True)),
                ('current_hospital', models.CharField(blank=True, max_length=100)),
                ('preferred_hospitals', models.JSONField(blank=True, default=list)),
                ('previous_transplants', models.IntegerField(default=0)),
                ('insurance_coverage', models.BooleanField(default=False)),
                ('smoking_status', models.CharField(choices=[('never', 'Never Smoked'), ('former', 'Former Smoker'), ('current', 'Current Smoker')], default='never', max_length=20)),
                ('alcohol_use', models.CharField(choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular')], default='never', max_length=20)),
                ('drug_use', models.BooleanField(default=False)),
                ('avg_sleep', models.FloatField(blank=True, null=True)),
                ('preferred_hospital', models.CharField(blank=True, max_length=255)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('max_travel_distance', models.IntegerField(default=100)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
