# Generated by Django 5.2.6 on 2025-09-26 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organs_donating', models.JSONField(default=list, help_text='Organs willing to donate')),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('smoking_status', models.CharField(choices=[('never', 'Never Smoked'), ('former', 'Former Smoker'), ('current', 'Current Smoker')], default='never', max_length=20)),
                ('alcohol_use', models.CharField(choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular')], default='never', max_length=20)),
                ('drug_use', models.BooleanField(default=False, help_text='History of drug use')),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('bmi', models.FloatField(blank=True, help_text='Body Mass Index', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Currently available for donation')),
                ('last_medical_checkup', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Any significant medical history')),
                ('willing_to_travel', models.BooleanField(default=True)),
                ('max_travel_distance', models.IntegerField(default=100, help_text='Maximum travel distance in miles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organs_needed', models.JSONField(default=list, help_text='Organs required')),
                ('urgency_level', models.CharField(choices=[('low', 'Low - Can wait months'), ('medium', 'Medium - Needs within weeks'), ('high', 'High - Needs within days'), ('critical', 'Critical - Immediate need')], default='medium', max_length=20)),
                ('medical_condition', models.TextField(help_text='Current medical condition')),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('current_treatment', models.TextField(blank=True, help_text='Current treatment plan')),
                ('preferred_hospitals', models.JSONField(default=list, help_text='Preferred hospitals for transplant')),
                ('current_hospital', models.CharField(blank=True, max_length=100)),
                ('previous_transplants', models.IntegerField(default=0)),
                ('insurance_coverage', models.BooleanField(default=False)),
                ('max_travel_distance', models.IntegerField(default=100, help_text='Maximum willing to travel in miles')),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
