# Generated by Django 5.2.6 on 2025-10-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='avg_sleep',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Sleep Hours'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, verbose_name='Insurance Provider'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_medical_check',
            field=models.DateField(blank=True, null=True, verbose_name='Last Medical Check'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='preferred_hospital',
            field=models.CharField(blank=True, max_length=255, verbose_name='Preferred Hospital'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='alcohol_use',
            field=models.BooleanField(blank=True, null=True, verbose_name='Alcohol Use'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='avg_sleep',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Sleep Hours'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='drug_use',
            field=models.BooleanField(blank=True, null=True, verbose_name='Drug Use'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, verbose_name='Insurance Provider'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='preferred_hospital',
            field=models.CharField(blank=True, max_length=255, verbose_name='Preferred Hospital'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='smoking_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Smoking Status'),
        ),
    ]
