# Generated by Django 5.2.6 on 2025-10-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_donorprofile_avg_sleep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientprofile',
            name='max_travel_distance',
            field=models.IntegerField(blank=True, default=100, help_text='Maximum willing to travel in miles'),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='preferred_hospitals',
            field=models.JSONField(blank=True, default=list, help_text='Preferred hospitals for transplant'),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='previous_transplants',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
