# Generated by Django 5.2.6 on 2025-10-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_recipientprofile_max_travel_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientprofile',
            name='preferred_hospitals',
            field=models.JSONField(blank=True, default=list, help_text='Preferred hospitals for transplant', null=True),
        ),
    ]
