# Generated by Django 5.2.6 on 2025-10-02 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(choices=[('kidney', 'Kidney'), ('liver', 'Liver'), ('heart', 'Heart'), ('lung', 'Lung'), ('pancreas', 'Pancreas'), ('intestine', 'Intestine')], max_length=20)),
                ('match_score', models.IntegerField(help_text='Compatibility score (0-100)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_matches', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('donor', 'recipient', 'organ_type')},
            },
        ),
    ]
