# Generated by Django 5.2.6 on 2025-10-02 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organmatch',
            name='donor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='donor_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organmatch',
            name='organs_matched',
            field=models.JSONField(default=list, help_text='List of organs that match'),
        ),
        migrations.AlterField(
            model_name='organmatch',
            name='recipient',
            field=models.ForeignKey(limit_choices_to={'user_type': 'recipient'}, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
